# Generated by Django 5.0.3 on 2024-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHING_STAFF', 'Teaching Staff'), ('NON_TEACHING_LAB_STAFF', 'Non Teaching Lab Staff'), ('NON_TEACHING_NON_LAB_STAFF', 'Non Teaching Non Lab Staff')], max_length=50),
        ),
    ]
