# Generated by Django 5.0.3 on 2024-03-24 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Leave Categories',
                'db_table': 'leave_categories',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('past', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave_category', models.ForeignKey(db_column='leave_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leavecategories')),
            ],
            options={
                'verbose_name_plural': 'Leave Applications',
                'db_table': 'leave_applications',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('leaves_remaining', models.IntegerField()),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave_category', models.ForeignKey(db_column='leaves_in_category1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leavecategories')),
            ],
        ),
    ]
