# Generated by Django 5.0.3 on 2024-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaveapplications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplications',
            name='which_half',
            field=models.CharField(choices=[('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half'), ('NONE', 'None')], default='NONE', max_length=20),
            preserve_default=False,
        ),
    ]
