# Generated by Django 4.2.6 on 2024-03-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leaveapplications_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplications',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
