# Generated by Django 5.0.3 on 2024-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_alter_leaveapplications_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplications',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
